#!/usr/bin/python3

import re

def is_valid_ip_address(ip_address):
    pattern = r'^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$'
    if re.match(pattern, ip_address):
        return True
    return False

# Testing the function
ip_addresses = [
    '192.168.0.1',
    'abc.def.ghi.jkl',
    '192.168.0.256',
]

for ip in ip_addresses:
    if is_valid_ip_address(ip):
        print(f"{ip} is a valid IP address.")
    else:
        print(f"{ip} is not a valid IP address.")
